### ISSUE TITLE
Cannot require in Laravel Installation

### ISSUE THREAD

**Issue by guyver4mk** [adldap/adLDAP#118]
When I run `composer require adldap\adldap "5.0.*"` on my Laravel Installation i'm getting the below error.

`The requested package adldap/adldap 5.0.* is satisfiable by adldap/adldap[5.0.0.x-dev] but these conflict with your requirements or minimum-stability.`

Also, when I include the package in the _require_, and _require-dev_ of my composer.json as `"adldap/adldap": "5.0.*"` I get the same error.

I have now been able to include the package by changing the require call in _require-dev_ to `"adldap/adldap": "@dev"`

Please could you update the composer versioning to accept the "5.0.*" release?

**Comment by strebl** [comment]
Don't use that package anymore! Switch to adlap2/adldap2. The old package isn't maintained anymore.
The new package is also more stable and has more features. There is also a Laravel package: adldap2/adldap2-laravel

Am 03.10.2016 um 11:37 schrieb Ciaran Moore <notifications@github.com<mailto:notifications@github.com>>:

When I run composer require adldap\adldap "5.0.*" on my Laravel Installation i'm getting the below error.

The requested package adldap/adldap 5.0.\* is satisfiable by adldap/adldap[5.0.0.x-dev] but these conflict with your requirements or minimum-stability.

Also, when I include the package in the require, and require-dev of my composer.json as "adldap/adldap": "5.0.*" I get the same error.

I have now been able to include the package by changing the require call in require-dev to "adldap/adldap": "@dev"

Please could you update the composer versioning to accept the "5.0.*" release?

##

**Comment by guyver4mk** [comment]
Ah, that would explain it!

Thanks for the quick response. I will change to adldap2 now 👍
