### ISSUE TITLE
Deprecated:  preg_replace(): The /e modifier is deprecated

### ISSUE THREAD

**Issue by geo4orce** [adldap/adLDAP#31]
using Version 4.0.3. Upgraded my PHP to v5.5.11 and now I keep getting:

    PHP Deprecated:  preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in /html/common/objects/adLDAP/classes/adLDAPUtils.php

**Comment by joedguarino** [comment]
I'm having this issue too. Trying to use for kayako implmentation. I updated to preg_replace_callback and remove the "e", but now it tells me  preg_replace_callback(): Requires argument 2, '&quot;\\\&quot;.join(&quot;&quot;,unpack(&quot;H2&quot;,&quot;$1&quot;))', to be a valid callback

**Comment by strebl** [comment]
You have to use the latest adldap version.

In version 4.0.4:
```php
public function ldapSlashes($str){
        return preg_replace('/([\x00-\x1F\*\(\)\\\\])/e',
                            '"\\\\\".join("",unpack("H2","$1"))',
                            $str);
    }
```

In the master branch:
```php
public function ldapSlashes($str) {
        return preg_replace_callback(
      		'/([\x00-\x1F\*\(\)\\\\])/',
        	function ($matches) {
            	return "\\".join("", unpack("H2", $matches[1]));
        	},
        	$str
    	);
    }
```
