### ISSUE TITLE
packagist.org lost your versions

### ISSUE THREAD

**Issue by webfractor** [adldap/adLDAP#79]
You no longer had any version other than dev-master available from packagist. This is breaking a lot of projects that depend on you.

```
"require": {
    "adldap/adldap": "~4.0",
}
```

This no longer resolves

**Comment by wunc** [comment]
See the following discussion for details on what happened: https://github.com/ztec/adLDAP/issues/5#issuecomment-112398824

**Comment by Wirone** [comment]
Alternatively you can use my "[fixfork](https://github.com/CoditoNet/adLDAP/tree/v4.0.4)" ;-)

**Comment by xelan** [comment]
@Rich2k 
Any update on this issue? [Packagist.org](https://packagist.org/packages/adldap/adldap) still has no tagged versions of adldap.

**Comment by rieschl** [comment]
It seems that Rich2k dropped the project. There's a new one continuing the work (including heavy work in progress) here: https://github.com/Adldap2/Adldap2
You can use the [4.0 release](https://github.com/Adldap2/Adldap2/tree/4.0) there instead of this one.
Maybe @stevebauman knows more about that?

**Comment by stevebauman** [comment]
I was granted write access, however I can't start pushing code into a repository to an owner who is seldom around in case something needs to be changed. I also don't have permissions to merge pull-requests by the looks of it.

**Comment by webfractor** [comment]
moved on...
