### ISSUE TITLE
Error on Composer Installation

### ISSUE THREAD

**Issue by AliAlGallaf** [adldap/adLDAP#87]
Upon trying to install adldap using Composer on a Laravel installation, I'm getting the below error.

```
C:\wamp\www\laravel>composer require adldap/adldap
Using version dev-master for adldap/adldap
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - adldap/adldap dev-master requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - adldap/adldap dev-master requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - Installation request for adldap/adldap dev-master -> satisfiable by adldap/adldap[dev-master].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by xelan** [comment]
Seems like you don't have the PHP LDAP extension installed and/or enabled. As you use WAMP on windows, you need to find your php.ini and uncomment the line

```
;php_ldap.dll
```

in the extensions section.See http://php.net/manual/en/install.windows.extensions.php for more details.

**Comment by AliAlGallaf** [comment]
Just checked php.ini file and php_ldap.dll is not commented out. I have been using adLDAP on other Laravel projects on the same server. I have installed adLDAP multiple times before with no issues, this is the first time that this error is appearing.

**Comment by xelan** [comment]
Does the LDAP access work if you install the packages witch `composer require --ignore-platform-reqs`?
https://getcomposer.org/doc/03-cli.md#require

**Comment by AliAlGallaf** [comment]
It worked but composer did not pull ext-ldap as it did when I previously used to install adLDAP.

**Comment by AliAlGallaf** [comment]
Composer was using a different PHP version that did not have LDAP enabled.
