### ISSUE TITLE
Class 'Adldap\Interfaces\ConnectionInterface' not found 

### ISSUE THREAD

**Issue by TiToMoskito** [adldap/adLDAP#94]
I have a problem, i cannot initalize Adldap.

Error Message: Fatal error: Class 'Adldap\Interfaces\ConnectionInterface' not found 

This is my code:
include dirname(**FILE**).'/Adldap/Adldap.php';
use Adldap\Adldap;

$config = array(
    'account_suffix' => '@test.int',
    'domain_controllers' => [''],
    'port' => 389,
    'base_dn' => ',
    'admin_username' => '',
    'admin_password' => '',
    'follow_referrals' => true,
    'use_ssl' => false,
    'use_tls' => false,
    'use_sso' => false,
);

$adLDAP = new Adldap($config);

$results = $adLDAP->search()
            ->where('OU', '=', 'Customers')
            ->all();
print_r($results);

**Comment by strebl** [comment]
Don't expect any help here... Switch to [Adldap2](https://github.com/Adldap2/Adldap2)!

**Comment by TiToMoskito** [comment]
But there i got an error with the same code, but this time this error:
Fatal error: Class 'Adldap\Connections\Configuration' not found in /var/www/vhosts/../.../base/Adldap/Adldap.php on line 44
